/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    RentalDeposit: {
      address: "0x59b670e9fA9D0A427751Af201D676719a970857b",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "leaseId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tenant",
              type: "address",
            },
          ],
          name: "DepositReturned",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "leaseId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "landlord",
              type: "address",
            },
          ],
          name: "DepositWithdrawn",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "leaseId",
              type: "uint256",
            },
          ],
          name: "LandlordApproved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "leaseId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "landlord",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tenant",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "depositAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "startDate",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "endDate",
              type: "uint256",
            },
          ],
          name: "LeaseCreated",
          type: "event",
        },
        {
          stateMutability: "payable",
          type: "fallback",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_leaseId",
              type: "uint256",
            },
          ],
          name: "approveDepositReturn",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_landlord",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_depositAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_startDate",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_endDate",
              type: "uint256",
            },
          ],
          name: "createLease",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "getLeaseCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_leaseId",
              type: "uint256",
            },
          ],
          name: "getLeaseDetails",
          outputs: [
            {
              internalType: "address",
              name: "landlord",
              type: "address",
            },
            {
              internalType: "address",
              name: "tenant",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "depositAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "startDate",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "endDate",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isActive",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "landlordApproved",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "leases",
          outputs: [
            {
              internalType: "address",
              name: "landlord",
              type: "address",
            },
            {
              internalType: "address",
              name: "tenant",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "depositAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "startDate",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "endDate",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isActive",
              type: "bool",
            },
            {
              internalType: "bool",
              name: "landlordApproved",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_leaseId",
              type: "uint256",
            },
          ],
          name: "returnDeposit",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_leaseId",
              type: "uint256",
            },
          ],
          name: "withdrawDeposit",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
